all: 
	$(MAKE) -C ./simple_gurobi
	$(MAKE) -C ./advanced_gurobi
build:
	$(MAKE) -C ./simple_gurobi build
	$(MAKE) -C ./advanced_gurobi build
run:
	$(MAKE) -C ./simple_gurobi run
	$(MAKE) -C ./advanced_gurobi run
clean:
	$(MAKE) -C ./simple_gurobi clean
	$(MAKE) -C ./advanced_gurobi clean
